# Diving in to explore PyTorch

### Basic functions related to torch.tensor

Pytorch is a python-based scientific computing package targeted as a replacement for NumPy to use the power of GPUs and
a deep learning research platform that provides maximum flexibility and speed.Lets discuss some of the basic functions for the PyTorch .

- torch.exp
- torch.narrow
- torch.digamma
- torch.flatten
- torch.mul

In [ ]:
# Import torch and other required modules
import torch
import math

## torch.exp
It takes input as a tensor.

Its gives the output tensor as the exponential of each element of the input tensor.

In [8]:
#Example -1
torch.exp(torch.tensor([0.,2.]))

tensor([1.0000, 7.3891])

It return a teensor consisting of exponential power of input tensor elements 0 and 2.

In [13]:
# Example 2
torch.exp(torch.tensor(math.log(4.)))

tensor(4.)

math.log(4.) gives out as log4 which when put in exponential return he same tensor 4.

In [16]:
# Example 3 - breaking 
torch.exp(torch.tensor([1,1]))

RuntimeError: exp_vml_cpu not implemented for 'Long'

torch.exp works with **Float tensor** not **LongTensor** when we implement tensor value as 1 it yields a LongTensor while 1.0 yields with FloatTensor.

troch.exp takes input as tensor and gives out as exponential tensor form of each element of input .Make sure to give input as FloatTensor

## torch.narrow

It take input of tensor,dimension along which the tensor has to be narrowed and starting and ending index of the dimension.

torch.arrow function returns a narrowed version of input tensor.

In [28]:
# Example 1 - working
x=torch.tensor([[1,2,3,4],[5,6,7,8],[7,8,9,10]])
              
torch.narrow(x,0,0,1)

tensor([[[1, 2],
         [2, 3],
         [3, 4],
         [4, 5],
         [5, 6],
         [6, 7]]])

This returns tensor narrowed around dimension 0 with length 2 ,startig from index =0

In [6]:
# Example 2 - working
x=torch.tensor([[1,2,3,4],[5,6,7,8],[7,8,9,10]])
              
torch.narrow(x,1,0,3)

This returns tensor narrowed around dimension 1 with length 3 ,startig from index =0 in inner array

In [7]:
# Example 3 - breaking 
x=torch.tensor([[1,2,3,4],[5,6,7,8],[7,8,9,10]])
              
torch.narrow(x,2,0,3)

Dimension of the given tensor is in range of [-2,1] thus ,dimension of 2 is not defined for this particular tensor

torch.narrow does not use any extra memory and is very fast.Any modification to narrowed will impact the orginal one.Remember that the last parameter in input defines the length.

## torch.digamma

It takes tensor as an input .

This function computes the logarithmic derivative of gamma function on input tensor.

In [8]:
# Example 1 - working
x=torch.tensor([1.,2.])
torch.digamma(x)

Formula used is  ψ(𝑥)=𝑑​𝑙𝑛(Γ(𝑥))​/𝑑𝑥

In [9]:
# Example 2 - working
x=torch.randn(4,3)
torch.digamma(x)

Tensor obatined from same dimension as the input tensor .The result is just obtained by applying the formula element wise on the input tensor.

In [5]:
# Example 3 - breaking 
x=torch.tensor([-1.,-2])
torch.digamma(x)

tensor([inf, inf])

Always keep in mind that the gamma function is always defined for postivie numbers .

Use this function when you need to compute logithmic of gamma function.

## torch.flatten


#### It accepts- 

input Tensor,start_dim(int)-the first dim to flatten,end_dim(int)-the last dim to flatten

Flattens the dimension of the matrix to a single dimension tensor.

In [12]:
# Example 1 - working
x=torch.randn(4,4)
torch.flatten(x)

tensor([ 0.0611,  0.2275, -0.5767, -1.8491,  0.0718,  0.4070,  1.3743,  0.6111,
         1.1703, -0.2264,  0.7025, -1.3122, -0.3543, -0.8586, -0.2346,  0.7988])

The random tensor generated had 16 elements in matrix form which has been flattened by the function and turned in single tensor with 16 elements in single dimension

In [26]:
# Example 2 - working
x=torch.rand(2,2)
torch.flatten(x,start_dim=1)

tensor([[0.9844, 0.4341],
        [0.5313, 0.5124]])

Dimension parameters can be choosen to get different levels of flatten tensor.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.randn(4,5)
torch.flatten(x,start_dim=1,end_dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Always keep the start_dim and end_dim in range of [-2,1]

Whenever we want to perform operations on the flattened tensor we can use this function.

## torch.mul

It accepts -:
Input tensor ,the second multiplication tensor.

This function is used for performing the multiplication of two tensors.

In [ ]:
# Example 1 
x=torch.randn(4,1)
torch.mul(x,100)

Tensor's each element gets multiplied by 100 

In [9]:
# Example 2 - working
x=torch.randn(3,1)
y=torch.randn(1,3)
torch.mul(x,y)

tensor([[ 0.4035, -0.6456, -0.4996],
        [ 0.9409, -1.5054, -1.1649],
        [-0.3491,  0.5586,  0.4323]])

Each element of first tensor is multipied with other element of the second tensor.

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.randn(2,3)
y=torch.randn(2,4)
torch.mul(x,y)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

Size of tensor 1 should match the size of tensor of 2 for this to work

Element wise multiplication is very necessary operation to take place and this function provides very convinent way to do so.

## Conclusion

Basic Pytorch was covered in this with 5 basic funtions and examples of their usage .Stay tuned for futher dive into neural networks using Pytorch.

## Reference Links

Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Notebook for '02-linear-regression' and '01-pytorch-basics':https://jovian.ml/aakashns

In [1]:
$ git config --global user.name "shwetanshutech"

SyntaxError: invalid syntax (<ipython-input-1-62c2ab5d7f77>, line 1)

In [3]:
import jovian

In [7]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "shwetanshu2000/01-tensor-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/shwetanshu2000/01-tensor-operations


'https://jovian.ml/shwetanshu2000/01-tensor-operations'